# Generated by Django 2.1.4 on 2018-12-17 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('studentmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Prüfung', 'verbose_name_plural': 'Prüfungen'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Ergebnis', 'verbose_name_plural': 'Ergebnisse'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Studenten'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Prüfungsnummer'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(6),
                                                                django.core.validators.MinValueValidator(1)],
                                      verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matriculation_number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Matrikelnummer'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
