# Generated by Django 2.1.4 on 2018-12-17 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanager', '0002_auto_20181217_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)], verbose_name='Note'),
        ),
    ]
